/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/About': RouteRecordInfo<'/About', '/About', Record<never, never>, Record<never, never>>,
    '/news/': RouteRecordInfo<'/news/', '/news', Record<never, never>, Record<never, never>>,
    '/news/dialogs/CardDialog': RouteRecordInfo<'/news/dialogs/CardDialog', '/news/dialogs/CardDialog', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/list/dialogs/Add': RouteRecordInfo<'/posts/list/dialogs/Add', '/posts/list/dialogs/Add', Record<never, never>, Record<never, never>>,
    '/posts/list/dialogs/Edit': RouteRecordInfo<'/posts/list/dialogs/Edit', '/posts/list/dialogs/Edit', Record<never, never>, Record<never, never>>,
    '/posts/list/List': RouteRecordInfo<'/posts/list/List', '/posts/list/List', Record<never, never>, Record<never, never>>,
  }
}
